PERMISSIONS = [
    ('DeviceBindingConfiguration', 'List'),
    ('DeviceBindingConfiguration', 'Create'),
    ('DeviceBindingSetting', 'Retrieve'),
    ('DeviceBindingSetting', 'Update'),
    ('BlockedDevice', 'List'),
    ('BlockedDevice', 'Create'),
    ('WhitelistedDevice', 'List'),
    ('WhitelistedDevice', 'Retrieve'),
    ('WhitelistedDevice', 'Create'),
    ('WhitelistedDevice', 'Delete'),
    ('UserDeviceStatus', 'Approve'),
    ('UserDeviceStatus', 'Reject'),
    ('UserDeviceStatus', 'List'),
    ('UserDeviceStatus', 'Retrieve'),
    ('UserDeviceStatus', 'Unlock'),
    ('UserDeviceStatus', 'Lock'),
    ('UserDeviceStatus', 'View Locked Account History'),
    ('UserLoginSession', 'List'),
    ('Device', 'Unlock'),
    ('Device', 'List'),
    ('User', 'View Passcode Locked'),
    ('User', 'Approve Passcode Locked'),
    ('User', 'View Inactive'),
    ('User', 'Approve Inactive'),
    ('User', 'Unblock'),
    ('User', 'List'),
    ('User', 'Retrieve'),
    ('User', 'Create'),
    ('User', 'Update'),
    ('User', 'Delete'),
    ('MessageAlert', 'List'),
    ('MessageAlert', 'Retrieve'),
    ('MessageAlert', 'Create'),
    ('MessageAlert', 'Update'),
    ('MessageAlert', 'Delete'),
    ('PushNotification', 'Send'),
    ('PushNotification', 'List'),
    ('PushNotification', 'Retrieve'),
    ('PushNotification', 'Create'),
    ('PushNotification', 'Update'),
    ('PushNotification', 'Delete'),
    ('NotificationList', 'List'),
    ('NotificationList', 'Retrieve'),
    ('NotificationList', 'Create'),
    ('NotificationList', 'Update'),
    ('NotificationList', 'Delete'),
    ('Language', 'List'),
    ('Language', 'Retrieve'),
    ('Language', 'Create'),
    ('Language', 'Update'),
    ('Language', 'Delete'),
    ('Country', 'List'),
    ('Country', 'Retrieve'),
    ('Country', 'Create'),
    ('Country', 'Update'),
    ('Country', 'Delete'),
    ('Company', 'List'),
    ('Company', 'Retrieve'),
    ('Company', 'Create'),
    ('Company', 'Update'),
    ('Company', 'Delete'),
    ('Agreement', 'List'),
    ('Agreement', 'Retrieve'),
    ('Agreement', 'Create'),
    ('Agreement', 'Update'),
    ('Agreement', 'Delete'),
    ('Brand', 'List'),
    ('Brand', 'Retrieve'),
    ('Brand', 'Create'),
    ('Brand', 'Update'),
    ('Brand', 'Delete'),
    ('OnboardingSession', 'Verify'),
    ('OnboardingSession', 'Reject'),
    ('OnboardingSession', 'List'),
    ('OnboardingSession', 'Retrieve'),
    ('OnboardingSession', 'Create'),
    ('OnboardingSession', 'Update'),
    ('OnboardingSession', 'Delete'),
    ('OnboardingSession', 'Idemia Sync'),
    ('OnboardingConfig', 'Retrieve'),
    ('OnboardingConfig', 'Update'),
    ('Customer', 'View Document Details'),
    ('Customer', 'Update Documents'),
    ('Customer', 'View Delete Account List'),
    ('Customer', 'View Qr Code'),
    ('Customer', 'Sync Data'),
    ('Customer', 'Customer Detail'),
    ('Customer', 'Invalid Customer Profile'),
    ('Customer', 'List'),
    ('Customer', 'Retrieve'),
    ('Customer', 'Create'),
    ('Customer', 'Update'),
    ('Customer', 'Delete'),
    ('Agent', 'List'),
    ('Agent', 'Retrieve'),
    ('Agent', 'Create'),
    ('Agent', 'Update'),
    ('Agent', 'Delete'),
    ('Branch', 'List'),
    ('Branch', 'Retrieve'),
    ('Branch', 'Create'),
    ('Branch', 'Update'),
    ('Branch', 'Delete'),
    ('PermissionPolicy', 'List'),
    ('PermissionPolicy', 'Retrieve'),
    ('PermissionPolicy', 'Create'),
    ('PermissionPolicy', 'Update'),
    ('PermissionPolicy', 'Delete'),
    ('ReferralCampaign', 'List'),
    ('ReferralCampaign', 'Retrieve'),
    ('ReferralCampaign', 'Create'),
    ('ReferralCampaign', 'Update'),
    ('ReferralCampaign', 'Delete'),
    ('SystemSetting', 'List'),
    ('SystemSetting', 'Retrieve'),
    ('SystemSetting', 'Create'),
    ('SystemSetting', 'Update'),
    ('SystemSetting', 'Delete'),
    ('ErrorMapping', 'List'),
    ('ErrorMapping', 'Retrieve'),
    ('ErrorMapping', 'Create'),
    ('ErrorMapping', 'Update'),
    ('ErrorMapping', 'Delete'),
    ('ServiceFee', 'List'),
    ('ServiceFee', 'Create'),
    ('ServiceFee', 'Update'),
    ('ServiceFee', 'Delete'),
    ('WalletUpdateConfiguration', 'Retrieve'),
    ('WalletUpdateConfiguration', 'Update'),
    ('Banner', 'List'),
    ('Banner', 'Retrieve'),
    ('Banner', 'Create'),
    ('Banner', 'Update'),
    ('Banner', 'Delete'),
    ('DocumentUpdateRequest', 'View Pending Customer List'),
    ('DocumentUpdateRequest', 'View Approved Rejected Customer List'),
    ('DocumentUpdateRequest', 'Change Document Status'),
    ('DocumentUpdateRequest', 'List'),
    ('DocumentUpdateRequest', 'Retrieve'),
    ('DocumentUpdateRequest', 'Create'),
    ('DocumentUpdateRequest', 'Update'),
    ('DocumentUpdateRequest', 'Delete'),
    ('EPayTransaction', 'View Pending Epay Transactions'),
    ('EPayTransaction', 'Change Epay Transaction Status'),
    ('EPayTransaction', 'Unlock Void Transaction'),
    ('EPayTransaction', 'Epay Wsdl Mock'),
    ('EPayTransaction', 'List'),
    ('EPayTransaction', 'Retrieve'),
    ('EPayTransaction', 'Create'),
    ('EPayTransaction', 'Update'),
    ('EPayTransaction', 'Delete')
]
